name: Package and Deploy to Lambda using base image

on:
  push:
    branches:
      - main
      - feature/refactor-project-to-hexagonal-architecture

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Get AWS Account ID
        id: aws
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Pull Docker image from ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ steps.aws.outputs.account_id }}.dkr.ecr.eu-west-1.amazonaws.com
          docker pull ${{ steps.aws.outputs.account_id }}.dkr.ecr.eu-west-1.amazonaws.com/trading-bot:latest

      - name: Create container and copy base package
        run: |
          docker create --name lambda-temp ${{ steps.aws.outputs.account_id }}.dkr.ecr.eu-west-1.amazonaws.com/trading-bot:latest
          docker cp lambda-temp:/package ./package
          docker rm lambda-temp

      - name: Inject latest source files into package
        run: |
          rsync -a src/ package/
          # Si tienes más archivos, agrégalos aquí
          cd package
          zip -r ../deployment.zip .

      - name: Upload ZIP to S3
        run: |
          aws s3 cp deployment.zip s3://lambda-functions-dev-serverlessdeploymentbucket-irlanda/trading-bot.zip

      - name: Update Lambda function "liquidity-sweep" from S3
        run: |
          aws lambda update-function-code \
            --function-name trading-bot-liquidity-sweep \
            --s3-bucket lambda-functions-dev-serverlessdeploymentbucket-irlanda \
            --s3-key trading-bot.zip

      - name: Update Lambda function "breakout-sol" from S3
        run: |
          aws lambda update-function-code \
            --function-name bot-breakout-sol \
            --s3-bucket lambda-functions-dev-serverlessdeploymentbucket-irlanda \
            --s3-key trading-bot.zip
