name: Deploy bot to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build deployment package on Amazon Linux
        run: |
          docker run --rm --platform linux/x86_64 \
            -v "$PWD":/var/task -w /var/task \
            public.ecr.aws/sam/build-python3.13:latest bash -c "
              set -e
              yum -y groupinstall 'Development Tools' &&
              yum -y install python3 python3-pip python3-devel gcc libffi-devel openssl-devel make zip &&
              python3 -m pip install --upgrade pip &&
              mkdir -p package &&
              python3 -m pip install -r requirements.txt -t package &&
              python3 -c 'import importlib.util, sys; spec = importlib.util.find_spec("_cffi_backend"); print("_cffi_backend found at:", spec.origin if spec else "not found"); sys.exit(1 if not spec else 0)' &&
              cp bot_trading.py package/ &&
              cd package &&
              zip -r ../deployment.zip .
            "

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # tu región

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name trading-bot-binance-64 \
            --zip-file fileb://deployment.zip

