name: Deploy bot to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # o la versión que uses

      - name: Install dependencies into package folder
        run: |
          mkdir package
          pip install -r requirements.txt -t package
          cp -r bot_trading.py package/

      - name: Zip package
        run: |
          cd package
          zip -r ../deployment.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # tu región

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name trading-bot-binance \
            --zip-file fileb://deployment.zip
