name: Deploy bot to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build deployment package on Amazon Linux
        run: |
          docker run --rm --platform linux/arm64 -v "$PWD":/var/task -w /var/task amazonlinux:2 bash -c "
            yum -y install python3 python3-pip zip &&
            python3 -m pip install --upgrade pip &&
            mkdir -p package &&
            pip3 install -r requirements.txt -t package &&
            cp bot_trading.py package/ &&
            cd package &&
            zip -r ../deployment.zip .
          "

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # tu región

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name trading-bot-binance \
            --zip-file fileb://deployment.zip
