name: Deploy bot to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image and package code
        run: |
          docker build -t lambda-bot .
          id=$(docker create lambda-bot)
          docker cp $id:/var/task ./package
          docker rm $id
          cd package
          zip -r ../deployment.zip ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # tu región

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name trading-bot-binance-64 \
            --zip-file fileb://deployment.zip

