name: One-time Docker Build & Push to ECR

on:
  push:
    branches:
      - dockerImage

jobs:
  ecr-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get AWS Account ID
        id: aws-account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

      - name: Create ECR repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names lambda-bot-trading || \
          aws ecr create-repository --repository-name lambda-bot-trading

      - name: Authenticate Docker to ECR
        run: |
          aws ecr get-login-password | docker login \
            --username AWS \
            --password-stdin ${{ steps.aws-account.outputs.account_id }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t lambda-bot-trading .

      - name: Tag Docker image
        run: |
          docker tag lambda-bot-trading:latest \
            ${{ steps.aws-account.outputs.account_id }}.dkr.ecr.us-east-1.amazonaws.com/lambda-bot-trading:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.aws-account.outputs.account_id }}.dkr.ecr.us-east-1.amazonaws.com/lambda-bot-trading:latest
